name: Prueba tokens

on:
  push:

jobs:
  comprobar-tokens:
    runs-on: self-hosted

    env:
      DEV_TOKEN: ${{ secrets.DEV_TOKEN }}

    steps:
      - name: Comparar tokens
        shell: cmd
        run: |
          if "%DEV_TOKEN%"=="%LOCAL_DEV_TOKEN%" (
            echo Los tokens coinciden
          ) else (
            echo Los tokens NO coinciden
            exit /b 1
          )
